# Generated by Django 5.0.1 on 2024-01-13 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customerr',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='Subscriber',
            new_name='Subscribe',
        ),
    ]
