# Generated by Django 5.0.1 on 2024-01-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_customerr_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='customers',
        ),
    ]
