# Generated by Django 5.0.1 on 2024-01-17 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_email_customer_customers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customers',
            new_name='image',
        ),
    ]
