# Generated by Django 5.0.1 on 2024-01-17 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rename_customers_customer_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='email',
            new_name='Email',
        ),
    ]
