# Generated by Django 5.0.1 on 2024-01-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_feature_rename_image_customer_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='icon_background',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
