# Generated by Django 5.0.1 on 2024-01-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_testimonial_videoblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='Is_featured',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='testimonial/logo'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
