# Generated by Django 5.0.1 on 2024-01-28 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_testimonial_is_featured_testimonial_company_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='Is_featured',
            new_name='is_featured',
        ),
    ]
