# Generated by Django 5.0.1 on 2024-01-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_blog_marketing_features_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='marketing_features',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='marketing_features',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
