# Generated by Django 5.0.1 on 2024-02-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_rename_logo_product_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hero_image',
            field=models.FileField(blank=True, null=True, upload_to='products/hero_images'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='studio', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='Content_type',
            field=models.CharField(choices=[('webinar', 'Webinar'), ('report', 'Report'), ('blog_post', 'Blog Post')], max_length=255),
        ),
    ]
