# Generated by Django 5.0.1 on 2024-02-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_product_hero_image_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
