# Generated by Django 5.0.1 on 2024-02-07 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_product_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.product'),
            preserve_default=False,
        ),
    ]
